filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/nginx/access*.log
  tags: ["site1-web"]

#---PARTIE SI UTILISATION DE MODULES-----
#setup.template.settings:
#  index.number_of_shards: 1

#setup.kibana:
#  host: "ELK:5601"
#----------------------------------------

#ENVOIE VERS SITE1-LOGSTASH
output.logstash:
  hosts: ["BUFFER:5044"]


processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
