filebeat.inputs:
- type: tcp
  max_message_size: 10MiB
  host: "localhost:9000" #ECOUTE CE QUI ARRIVE SUR LE PORT 9000


setup.kibana: #On le laisse activé sur on veut faire des setup de modules (exemple PARTIE VI Module Nginx)
  host: "ELK:5601"

#output.elasticsearch:
  # Array of hosts to connect to.
  #hosts: ["ELK:9200"]

output.logstash:
  hosts: ["ELK:5044"]
processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

