version: '2'
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:7.12.0
    container_name: logstash
    ports:
      - 5044:5044
    networks:
      - elastic


#AJOUT DE LOGTASH DANS LE MEME RESEAU QUE ELASTICSEARCH ET KIBANA
networks:
  elastic:
    driver: bridge