filebeat.inputs:
- type: container
  paths: 
    - '/var/lib/docker/containers/*/*.log'

setup.kibana: #On le laisse activé sur on veut faire des setup de modules (exemple PARTIE VI Module Nginx)
  host: "ELK:5601"

#output.elasticsearch:
  # Array of hosts to connect to.
  #hosts: ["ELK:9200"]

output.logstash:
  hosts: ["ELK:5044"]
processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

